# Generated by Django 3.1.2 on 2020-10-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('distancia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('caoPequenoFDS', models.DecimalField(decimal_places=2, max_digits=5)),
                ('caoGrandeFDS', models.DecimalField(decimal_places=2, max_digits=5)),
                ('caoPequeno', models.DecimalField(decimal_places=2, max_digits=5)),
                ('caoGrande', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'canil',
            },
        ),
        migrations.DeleteModel(
            name='Music',
        ),
    ]
